# Generated by Django 4.2.2 on 2023-06-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_characters_character_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='char_id',
            new_name='character_id',
        ),
    ]
