# Generated by Django 4.2.2 on 2023-06-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_char_id_character_character_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
