# Generated by Django 4.2.2 on 2023-06-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_character_description_character_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.CharField(max_length=305),
        ),
    ]
