# Generated by Django 4.2.2 on 2023-06-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_character_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='teams',
            field=models.ManyToManyField(blank=True, to='main_app.team'),
        ),
    ]
